version: '2'
services:
  database:
    image: influxdb:1.4-alpine
    ports:
      - 8086:8086
      - 8089:8089
    volumes:
      - /opt/arduino/influxdb:/var/lib/influxdb
      - /opt/arduino/conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_DB=weather
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER=password
    restart: always
  dashboard:
    image: grafana/grafana:4.6.2
    ports:
      - 3000:3000
    volumes:
      - /opt/arduino/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    restart: always
