apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
  - name: "8086"
    port: 8086
    targetPort: 8086
  - name: "8089"
    port: 8089
    targetPort: 8089
  selector:
    io.kompose.service: database
status:
  loadBalancer: {}
