apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_USER
          value: password
        - name: INFLUXDB_DB
          value: weather
        image: influxdb:1.4-alpine
        name: database
        ports:
        - containerPort: 8086
        - containerPort: 8089
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: database-claim0
        - mountPath: /etc/influxdb/influxdb.conf
          name: database-claim1
      restartPolicy: Always
      volumes:
      - name: database-claim0
        persistentVolumeClaim:
          claimName: database-claim0
      - name: database-claim1
        persistentVolumeClaim:
          claimName: database-claim1
status: {}
